In [5]:
import numpy as np

nomes  = np.array(['Bob','Joe','Bob','Will'])

data = np.random.randn(4, 4)

In [6]:
data

array([[-0.99058023,  0.6716134 ,  0.55421391, -0.37532876],
       [ 0.33867267, -2.31137157,  1.55731837,  0.85773603],
       [ 0.77407555, -1.77658712, -0.35562301, -0.80297662],
       [ 0.27881849, -0.64348303,  0.30261817,  0.87850708]])

In [7]:
nomes == 'Bob'

array([ True, False,  True, False])

In [8]:
data[nomes == 'Bob']

array([[-0.99058023,  0.6716134 ,  0.55421391, -0.37532876],
       [ 0.77407555, -1.77658712, -0.35562301, -0.80297662]])

In [9]:
data[nomes == 'Bob',2:]

array([[ 0.55421391, -0.37532876],
       [-0.35562301, -0.80297662]])

In [10]:
data[data<0] = 0

In [11]:
data

array([[0.        , 0.6716134 , 0.55421391, 0.        ],
       [0.33867267, 0.        , 1.55731837, 0.85773603],
       [0.77407555, 0.        , 0.        , 0.        ],
       [0.27881849, 0.        , 0.30261817, 0.87850708]])

In [12]:
data[nomes != 'Joe'] = 8

In [13]:
data

array([[8.        , 8.        , 8.        , 8.        ],
       [0.33867267, 0.        , 1.55731837, 0.85773603],
       [8.        , 8.        , 8.        , 8.        ],
       [8.        , 8.        , 8.        , 8.        ]])