<h1>Numerical Python</h1>
<ul>
<li>foi projetado para ser eficaz em arrays de dados grandes</li>
<li>arrays numpy utilizam menos memória que as sequências embutidas em python</li>
<li>operações do numpy realizam processamentos complexos em arrays inteiros sem a necessidade de laços for</li>
</ul>

In [3]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 27.1 ms


In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 717 ms


In [9]:
#algoritmos baseados em numpy geralmente ssão de 10 a 100 vezes mais rápidos (ou mais) do que suas contrapartidas em Python puro, além de utilizarem significativamente menos memória

<h4>objeto array n-dimensional</h4>

In [10]:
#pequeno array de dados aleatórios é gerado
data = np.random.randn(2,3)

In [11]:
data

array([[-1.09646785, -0.82978395, -0.71598957],
       [ 2.09772663, -1.97361696, -0.27481484]])

In [12]:
data

array([[-1.09646785, -0.82978395, -0.71598957],
       [ 2.09772663, -1.97361696, -0.27481484]])

In [13]:
data*2

array([[-2.1929357 , -1.6595679 , -1.43197913],
       [ 4.19545327, -3.94723392, -0.54962969]])

In [14]:
data + data

array([[-2.1929357 , -1.6595679 , -1.43197913],
       [ 4.19545327, -3.94723392, -0.54962969]])

In [15]:
#os dados no ndarray devem ser homogêneos!

In [16]:
#todo array tem um shape, uma tupla que indica o tamanho de cada dimensão
#há também um dtype, um objeto que descreve o tipo de dados do array

In [17]:
data.shape

(2, 3)

In [19]:
data.dtype

dtype('float64')

In [20]:
#CRIANDO ARRAYS

In [21]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)


In [22]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)

In [24]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr2.ndim

2

In [26]:
#arr2 tem duas dimensões

In [27]:
arr2.shape

(2, 4)

In [28]:
arr2.dtype

dtype('int32')

In [29]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
a = np.zeros((3,6))

In [31]:
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
b = np.empty((2,3,2))
b

array([[[8.33759576e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [7.56587583e-307, 3.38299837e-061]],

       [[4.91414622e-062, 5.10270408e-066],
        [1.31323495e-047, 1.18921972e-047],
        [2.36081727e+184, 7.93161572e-067]]])

In [36]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#dtype

In [39]:
arr = np.array([3.4, -1.2,4.9])
arr2 = arr.astype(np.int32)
arr2

array([ 3, -1,  4])

In [40]:
numeric_strings = np.array(['25','3.4'], dtype=np.string_)

In [41]:
numeric_strings.astype(float)

array([25. ,  3.4])

In [42]:
#chamar astype sempre cria um novo array(uma cópia dos dados), mesmo que o novo dtype seja igual ao dtype antigo

In [43]:
novo_array = np.array([[1,2,3],[4,5,6]])

In [44]:
novo_array*novo_array

array([[ 1,  4,  9],
       [16, 25, 36]])

In [45]:
novo_array-novo_array

array([[0, 0, 0],
       [0, 0, 0]])

In [46]:
1/novo_array

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [49]:
outro_array = np.array([[1,2,0],[1.4,5,3]])

In [50]:
novo_array

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
novo_array == outro_array

array([[ True,  True, False],
       [False,  True, False]])